import smtplib
import pandas as pd
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
from datetime import date

# 1. Load Secrets
load_dotenv()
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASS = os.getenv("EMAIL_PASS")
RECEIVER_EMAIL = EMAIL_USER 

# 2. Read the Top Matches
try:
    df = pd.read_csv("best_matches.csv")
    top_jobs = df.head(3)
except FileNotFoundError:
    print("No matches found. Run match.py first!")
    exit()

# 3. Create the Email Content (HTML)
today = date.today().strftime("%B %d, %Y")

html_content = f"""
<html>
  <body style="font-family: Arial, sans-serif;">
    <h2 style="color: #2c3e50;">🚀 Job Sniper Daily Briefing: {today}</h2>
    <p>Good morning Giacomo. Here are the top 3 roles matching your profile today:</p>
    <table border="1" cellpadding="10" cellspacing="0" style="border-collapse: collapse; width: 100%; border: 1px solid #ddd;">
      <tr style="background-color: #f2f2f2; text-align: left;">
        <th>Score</th>
        <th>Role</th>
        <th>Company</th>
        <th>Location</th>
        <th>Action</th>
      </tr>
"""

for index, row in top_jobs.iterrows():
    # Convert score to percentage
    score = int(row['match_score'] * 100)
    
    # Color code the score
    color = "green" if score > 70 else "orange"
    if score < 60: color = "red"
    
    html_content += f"""
      <tr>
        <td style="color: {color}; font-weight: bold;">{score}%</td>
        <td>{row['job_title']}</td>
        <td>{row['employer_name']}</td>
        <td>{row['job_location']}</td>  <td><a href="{row['job_apply_link']}" style="background-color: #3498db; color: white; padding: 5px 10px; text-decoration: none; border-radius: 3px;">Apply Now</a></td>
      </tr>
    """

html_content += """
    </table>
    <p style="margin-top: 20px; font-size: 12px; color: #7f8c8d;"><i>Generated by your Python Job Sniper 🎯</i></p>
  </body>
</html>
"""

# 4. Send the Email
msg = MIMEMultipart()
msg['From'] = "Job Sniper Bot"
msg['To'] = RECEIVER_EMAIL
msg['Subject'] = f"🎯 Daily Job Matches for {today}"
msg.attach(MIMEText(html_content, 'html'))

try:
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(EMAIL_USER, EMAIL_PASS)
    server.sendmail(EMAIL_USER, RECEIVER_EMAIL, msg.as_string())
    server.quit()
    print("✅ Email sent successfully! Check your inbox.")
except Exception as e:
    print(f"❌ Error sending email: {e}")